name: 'clj-kondo checks'
description: 'Lint your clojure code with clj-kondo in parallel to your builds'
author: 'DeLaGuardo'
branding:
  icon: 'gift'
  color: 'blue'
inputs:
  clj-kondo-args:
    description: 'Arguments to be passed to clj-kondo'
    required: true
    default: '--lint src'
  check-name:
    description: 'Check name will be visible in Github Checks list'
    default: 'clj-jondo check'
  github_token:
    description: 'Github token to report linter results back to check'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    CHECK_NAME: ${{ inputs.check-name }}
    LINT_ARGS: ${{ inputs.clj-kondo-args }}
